# Generated by Django 4.1.5 on 2023-02-06 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1029_alter_document_archive_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='prefix'),
        ),
        migrations.AlterField(
            model_name='document',
            name='archive_serial_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The position of this document in your physical document archive.', null=True, validators=[django.core.validators.MaxValueValidator(4294967295), django.core.validators.MinValueValidator(0)], verbose_name='archive serial number'),
        ),
    ]
