# Generated by Django 4.1.5 on 2023-03-02 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1030_documenttype_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='added'),
        ),
    ]
