# Generated by Django 4.2.7 on 2023-12-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1032_change_asn'),
        ('documents', '1042_consumptiontemplate_assign_custom_fields_and_more'),
    ]

    operations = [
    ]
